///////////////////////////////////////////////////////////////////////////
// Description: Data Access class for the table 'Users'
// Generated by LLBLGen v1.3.5996.26197 Final on: Monday, March 21, 2022, 12:13:32 AM
// Because the Base Class already implements IDispose, this class doesn't.
///////////////////////////////////////////////////////////////////////////
using System;
using System.Data;
using System.Data.SqlTypes;
using System.Data.SqlClient;

namespace GasToanMy
{
	/// <summary>
	/// Purpose: Data Access class for the table 'Users'.
	/// </summary>
	public partial class clsUsers : clsDBInteractionBase
	{

		public DataTable Users_Login()
		{
			SqlCommand scmCmdToExecute = new SqlCommand();
			scmCmdToExecute.CommandText = "dbo.[Users_Login]";
			scmCmdToExecute.CommandType = CommandType.StoredProcedure;
			DataTable dtToReturn = new DataTable("Users");
			SqlDataAdapter sdaAdapter = new SqlDataAdapter(scmCmdToExecute);

			// Use base class' connection object
			scmCmdToExecute.Connection = m_scoMainConnection;

			try
			{
				m_scoMainConnection.Open();

				scmCmdToExecute.Parameters.Add(new SqlParameter("@sAcountName", SqlDbType.NVarChar, 50, ParameterDirection.Input, false, 0, 0, "", DataRowVersion.Proposed, m_sAcountName));
				scmCmdToExecute.Parameters.Add(new SqlParameter("@sPassword", SqlDbType.NVarChar, 50, ParameterDirection.Input, false, 0, 0, "", DataRowVersion.Proposed, m_sPassword));

				// Execute query.
				sdaAdapter.Fill(dtToReturn);
				return dtToReturn;
			}
			catch (Exception ex)
			{
				// some error occured. Bubble it to caller and encapsulate Exception object
				throw new Exception("Users_Login", ex);
			}
			finally
			{
				//Close connection.
				m_scoMainConnection.Close();
				scmCmdToExecute.Dispose();
				sdaAdapter.Dispose();
			}
		}
	}
}
